name: Run Python Script with Cache
run-name: ${{ github.actor }} is running the Python update script

on: 
  schedule:
    - cron: "45 * * * *"

jobs:
  Update_data:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - run: echo "${{ github.repository }} repository has been cloned to the runner."

      - name: Cache Python packages
        uses: actions/cache@v2
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'  # Replace '3.x' with the desired Python version

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt  # Replace with your requirements file

      - name: Run Python script
        run: python update_data.py
        
      - name: Finished
      - run: echo "This job's status is ${{ job.status }}."
